```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Remediate S3 general purpose buckets should have Lifecycle configurations'
Parameters:
  TargetResource:
    Type: String
Resources:
  RemediationDocument:
    Type: 'AWS::SSM::Document'
    Properties:
      DocumentType: 'Automation'
      Content:
        schemaVersion: '0.3'
        mainSteps:
          - name: 'RemediateFinding'
            action: 'aws:executeAwsApi'
            inputs:
              Service: S3
              Api: PutBucketLifecycleConfiguration
              Bucket: '{{TargetResource}}'
              LifecycleConfiguration:
                Rules:
                  - ID: DefaultLifecycleRule
                    Status: Enabled
                    Transitions:
                      - Days: 30
                        StorageClass: STANDARD_IA
```